### ISSUE TITLE
Test Flake: `//test/integration:health_check_integration_test` on Windows

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#16976]
Test `//test/integration:health_check_integration_test`  is flaky on Windows

See run https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/78892/logs/169

Error stack trace:
```
2021-06-13T20:10:35.8493433Z [ RUN      ] IpHttpVersions/HttpHealthCheckIntegrationTest.SingleEndpointImmediateHealthcheckFailHttp/IPv6_Http2Upstream
2021-06-13T20:10:35.8494200Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8494839Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8495472Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8496489Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8497134Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8497764Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8498404Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8499036Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8499669Z TestRandomGenerator running with seed 1417999120
2021-06-13T20:10:35.8500568Z test/integration/health_check_integration_test.cc(276): error: Value of: clusters_[cluster_idx].host_fake_connection_->waitForNewStream( *dispatcher_, clusters_[cluster_idx].host_stream_)
2021-06-13T20:10:35.8501494Z   Actual: false (Timed out waiting for new stream.)
2021-06-13T20:10:35.8502097Z Expected: true
2021-06-13T20:10:35.8502624Z Stack trace:
2021-06-13T20:10:35.8503470Z   00007FF65B3384A6: (unknown)
2021-06-13T20:10:35.8504108Z   00007FF65B351528: (unknown)
2021-06-13T20:10:35.8504703Z   00007FF65B3516ED: (unknown)
2021-06-13T20:10:35.8505295Z   00007FF65B35214D: (unknown)
2021-06-13T20:10:35.8507891Z ... Google Test internal frames ...
2021-06-13T20:10:35.8508478Z 
2021-06-13T20:10:35.8509331Z [  FAILED  ] IpHttpVersions/HttpHealthCheckIntegrationTest.SingleEndpointImmediateHealthcheckFailHttp/IPv6_Http2Upstream, where GetParam() = 8-byte object <01-00 00-00 01-00 00-00> (10080 ms)
```

I validated that I can repro it fairly consistently on my local devbox

**Comment by davinci26** [comment]
I did a binary search on the latest commits and I see that this is caused by https://github.com/envoyproxy/envoy/pull/16821

I am not 100% sure how these two are connected, I will have to look into it more.

**Comment by davinci26** [comment]
closed by ##16980
