### ISSUE TITLE
Envoy fails to build with GCC 7.2

### ISSUE THREAD

**Issue by jrajahalme** [envoyproxy/envoy#2987]
Title: Envoy build fails with GCC 7.2.

Description:
```
ERROR: /root/.cache/bazel/_bazel_root/e3bb2978717df7858b43846d8c1242eb/external/envoy/source/common/upstream/BUILD:334:1: C++ compilation of rule '@envoy//source/common/upstream:upstream_lib' failed (Exit 1)
external/envoy/source/common/upstream/upstream_impl.cc: In static member function 'static Envoy::Network::ClientConnectionPtr Envoy::Upstream::HostImpl::createConnection(Envoy::Event::Dispatcher&, const Envoy::Upstream::ClusterInfo&, Envoy::Network::Address::InstanceConstSharedPtr, const OptionsSharedPtr&)':
external/envoy/source/common/upstream/upstream_impl.cc:80:67: error: '*((void*)& iftmp.712 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                           : absl::optional<bool>{}) {}
                                                                   ^
cc1plus: all warnings being treated as errors
Target //:envoy_deps failed to build
```

The failure happens due to the compiler issuing the `maybe-uninitialized` warning (enabled via `-Wall`), which is considered as an error due to `-Werror` compiler option. GCC, however, reserves the freedom of issuing false positive `maybe-uninitialized` warnings (hence the 'maybe-'), and apparently clang does not turn on `maybe-uninitialized` warning via `-Wall` for this reason.

This seems to be a well-known issue affecting `std`, `boost` and `absl` variants of `optional`, see, e.g., https://stackoverflow.com/questions/21755206/how-to-get-around-gcc-void-b-4-may-be-used-uninitialized-in-this-funct.

A potential solution would be to not issue `maybe-uninitialized` warnings also with gcc by setting `-Wno-maybe-uninitialized` after `-Wall` or at least not considering them as errors by adding the option `-Wno-error=maybe-uninitialized` after `-Werror`.

**Comment by jrajahalme** [comment]
Even though this now manifests with gcc 7.2, there are no guarantees that similar issues do not appear with gcc 5.4 later.

**Comment by mattklein123** [comment]
This is unfortunate. @htuch @jmarantz can we loop in someone from abseil to figure out the recommended way of handling?

**Comment by jrajahalme** [comment]
One option would be to use compiler `#pragma` lines to suppress these false positive warnings/errors on affected code lines on a case-by-case basis but that can get ugly over time. Upon a quick glance I did not find such `#pragma`s in Envoy sources yet.

**Comment by jrajahalme** [comment]
Downgrading the compiler to gcc 5 can also be painful, as on Ubuntu 17.10 gcc 5 is broken in a way that breaks the build of Envoy dependencies (https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1725848).

**Comment by moderation** [comment]
Thanks for digging into this. I reported this initially on Slack at https://envoyproxy.slack.com/archives/C78HA81DH/p1522460801000007. I can confirm that adding the `-Wno-error=maybe-uninitialized` flag to `bazel/envoy_build_system.bzl` still reports the error but allows a successful compilation.
