### ISSUE TITLE
Build results in Protobuf errors

### ISSUE THREAD

**Issue by Jenkins-J** [envoyproxy/envoy#37266]
*Title*: Building envoy results in protobuf compile errors

*Description*:
When attempting to build envoy, the build fails with the below errors related to protobuf.
`bazel build --subcommands --cpu=ppc --sandbox_debug --action_env=CC=clang-14 --action_env=CXX=clang++-14 --linkopt=-fuse-ld=lld-14 --verbose_failures --define=boringssl=fips //source/exe:envoy-static`
```
In file included from external/com_google_protobuf/src/google/protobuf/util/field_mask_util.cc:8:
In file included from bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/field_mask_util/google/protobuf/util/field_mask_util.
h:17:
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:166:3: e
rror: unknown type name 'PROTOBUF_ATTRIBUTE_REINITIALIZES'
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  ^
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:173:29:
error: only virtual member functions can be marked 'final'
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }
                            ^~~~~~
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:178:38:
error: only virtual member functions can be marked 'final'
  void SetCachedSize(int size) const final;
                                     ^~~~~
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:92:9: 
error: use of undeclared identifier 'GetOwningArena'
    if (GetOwningArena() == from.GetOwningArena()
        ^
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:92:34: 
error: no member named 'GetOwningArena' in 'google::protobuf::FieldMask'
    if (GetOwningArena() == from.GetOwningArena()
                            ~~~~ ^
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:139:9: 
error: use of undeclared identifier 'GetOwningArena'
    if (GetOwningArena() == other->GetOwningArena()) {
        ^
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:139:36: 
error: no member named 'GetOwningArena' in 'google::protobuf::FieldMask'
    if (GetOwningArena() == other->GetOwningArena()) {
                            ~~~~~  ^
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:148:17: 
error: use of undeclared identifier 'GetOwningArena'
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
                ^
bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto/google/protobuf/field_mask.pb.h:148:44: 
error: no member named 'GetOwningArena' in 'google::protobuf::FieldMask'
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
                                    ~~~~~  ^
```

All of the errors appear to be in a file (field_mask.pb.h) that is generated by the protobuf build process:
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/field_mask.proto
```

Using bazel query, I've found the dependency path to the failing protobuf target:
```
//source/exe:envoy-static
//source/exe:envoy_main_entry_lib
//source/server:options_lib
@envoy_api//envoy/admin/v3:pkg_cc_proto
@com_google_protobuf//:protobuf
@com_google_protobuf//src/google/protobuf:protobuf_layering_check_legacy
@com_google_protobuf//src/google/protobuf/util:field_mask_util
```

Envoy version (from VERSION.txt): 1.32.0-dev

Any information would be helpful.
Thank you

**Comment by soulxu** [comment]
cc @phlax

**Comment by Jenkins-J** [comment]
To ensure the Protobuf repository was not the cause of the issue, I cloned the Protobuf repository separately and was able to build the target successfully. (I built Protobuf version 26.1, the same version that Envoy was building when the failures above occurred).

**Comment by phlax** [comment]
apologies i missed this - not sure exactly what the issue is

if protobuf can build independently - _might_ be worth checking the `bazel/protobuf.patch` to see if anything there is at issue

**Comment by phlax** [comment]
also - i guess you might want to check what flags are being set when you build in envoy/independently

**Comment by Jenkins-J** [comment]
While debugging, I also noticed that in the `external` directory of the bazel cache there are two directories, `com_google_protobuf` and `protobuf~`. They appear to contain the same files, but the files differ from each other in slight ways (for example `PROTOBUF_ATTRIBUTE_REINITIALIZES` is defined in a file under `protobuf~` but is not defined in the same file under `com_google_protobuf`.

Are both of these directories expected to exist in the bazel cache?

**Comment by Jenkins-J** [comment]
@phlax I found in my bazel cache that there are two different protoc binaries created:

```
./execroot/_main/bazel-out/ppc-opt-exec-ST-d57f47055a04/bin/external/protobuf~/protoc
./external/com_google_protobuf_protoc_linux_ppcle_64/bin/protoc
```

When running the binaries with the `--version` flag I get two different versions, but the binary under the `com_google_protobuf_protoc_linux_ppcle_64` directory is the correct version (26.1).

I believe that somehow the other protoc binary is being used to compile protobuf files during the build.
I know how the binary under the `com_google_protobuf_protoc_linux_ppcle_64` directory is created (generated by the `_compiled_protoc_deps function`), but I do not know where the other binary is coming from.

Do you happen to know how the other binary is getting created or how to ensure that the proper protoc binary is used to compile protobuf files during the build?

**Comment by Jenkins-J** [comment]
Issue resolved. I was using Bazel modules in addition to the WORKSPACE file to load dependencies. Once I saw that the `common --noenable_bzlmod` option is supposed to be set in the .bazelrc, I disabled bazel modules and the conflict no longer occurs. Using bzlmod in addition to loading dependencies via the WORKSPACE file must have caused multiple versions of the protobuf dependency to be loaded.
