### ISSUE TITLE
compile_time_options CI job fails with the latest Abseil lib

### ISSUE THREAD

**Issue by rojkov** [envoyproxy/envoy#13973]
*Title*: *compile_time_options CI job fails with the latest Abseil lib*

*Description*:
The int128 support in SimpleAtoi introduced in https://github.com/abseil/abseil-cpp/commit/4b915e70929ca2d6152240facc83d3d38c5d5f28 triggers this bug in Clang: [__int128_t multiply with -fsanitize=undefined fails to link (undefined reference to __muloti4)](https://bugs.llvm.org/show_bug.cgi?id=16404)

*Repro steps*:
1. update Abseil to the latest master in `bazel/repository_locations.bzl`;
2. run `ci/run_envoy_docker.sh 'ci/do_ci.sh bazel.compile_time_options'`

*Logs*:
The result can be seen in this CI job's log https://dev.azure.com/cncf/envoy/_build/results?buildId=56675&view=logs&jobId=e969334a-0e55-5c18-ac96-8b546753391e&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57
```
2020-11-05T15:34:46.1334065Z ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy/test/integration/BUILD:254:14: Linking of rule '@envoy//test/integration:hotrestart_test' failed (Exit 1): clang failed: error executing command 
2020-11-05T15:34:46.1335612Z   (cd /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy && \
2020-11-05T15:34:46.1336305Z   exec env - \
2020-11-05T15:34:46.1336703Z     BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
2020-11-05T15:34:46.1337306Z     BAZEL_LINKLIBS=-l%:libstdc++.a \
2020-11-05T15:34:46.1337873Z     BAZEL_LINKOPTS=-lm \
2020-11-05T15:34:46.1338251Z     CC=clang \
2020-11-05T15:34:46.1338572Z     CXX=clang++ \
2020-11-05T15:34:46.1338900Z     ENVOY_ASAN=1 \
2020-11-05T15:34:46.1339237Z     ENVOY_UBSAN_VPTR=1 \
2020-11-05T15:34:46.1339644Z     PATH=/usr/sbin:/usr/bin:/sbin:/bin:/opt/llvm/bin \
2020-11-05T15:34:46.1340034Z     PWD=/proc/self/cwd \
2020-11-05T15:34:46.1340759Z   /opt/llvm/bin/clang @bazel-out/k8-dbg/bin/external/envoy/test/integration/hotrestart_test-2.params)
2020-11-05T15:34:46.1341345Z Execution platform: @rbe_ubuntu_clang//config:platform
2020-11-05T15:34:46.1341798Z ld.lld: error: undefined symbol: __muloti4
2020-11-05T15:34:46.1342380Z >>> referenced by int128_have_intrinsic.inc:251 (external/com_google_absl/absl/numeric/int128_have_intrinsic.inc:251)
2020-11-05T15:34:46.1343451Z >>>               bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/_objs/strings/numbers.pic.o:(absl::operator*(absl::int128, absl::int128))
2020-11-05T15:34:46.1344374Z clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lizan** [comment]
Seems like it's an abseil issue? Can you open an issue there too?

**Comment by rojkov** [comment]
Yeap, filed https://github.com/abseil/abseil-cpp/issues/841

**Comment by derekmauro** [comment]
If I recall correctly, Abseil also ran into this problem. I think the solution was to pass `--copt=-fsanitize-link-c++-runtime --linkopt=-fsanitize-link-c++-runtime` to Bazel in the sanitizer build.

**Comment by rojkov** [comment]
@derekmauro Thank you! It looks like in our case it's enough to enforce linking with libc++ instead of libstdc++ when sanitizers are enabled. I'll submit a patch to Envoy.
