### PR TITLE
mobile/ci: Fix workflow dependencies

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
not sure if this was a bad merge, or how it got through CI, i had to fix the same on the pr for the android build

**Comment by phlax** [comment]
@alyssawilk afaict there is another permafail here:

```console
external/envoy/test/integration/ssl_utility.cc:12:10: fatal error: 'test/config/utility.h' file not found
#include "test/config/utility.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/envoyproxy/envoy/actions/runs/5065551466/jobs/9094259070?pr=27592#step:5:102

the changes in this PR are required i think so i will push it through, and will try and track where it started
