### ISSUE TITLE
Upgrading to gRPC 1.17.2 requires ALTS code change

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#5461]
*Title*: Upgrading to gRPC 1.17.2 requires ALTS code change

*Description*: While testing some updated dependencies including gRPC 1.17.2, I found that the Envoy ALTS code will need to change to accommodate change in the external dependency gRPC code.

[*Relevant Links*:]
https://github.com/grpc/grpc/commit/285d4ef1be44a15235b734a1e476fb8af4d71c79#diff-db966a87fffefb50d7a0446f10fbb424 adds a `pollset_set` to the ALTS TSI handshaker.

*Repro steps*:
After upgrading the gRPC dependency to 1.17.2 and running tests the following failure is observed:
```
source/extensions/transport_sockets/alts/config.cc:87:25: error: no matching function for call to 'alts_tsi_handshaker_create'
    tsi_result status = alts_tsi_handshaker_create(
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_github_grpc_grpc/src/core/tsi/alts/handshaker/alts_tsi_handshaker.h:60:12: note: candidate function not viable: requires 6 arguments, but 5 were provided
tsi_result alts_tsi_handshaker_create(
           ^
1 error generated.
```
/cc @lizan who did a lot of the original ALTS work and @htuch

**Comment by lizan** [comment]
@moderation as a temporary solution to unblock that PR, would passing `nullptr` work?

cc @JimmyCYJ @qiwzhang

**Comment by JimmyCYJ** [comment]
There is a change to alts in the latest gRPC library.
https://github.com/grpc/grpc/pull/16773/files#diff-15 introduced two methods,
grpc_alts_shared_resource_dedicated_init(), and
grpc_alts_shared_resource_dedicated_shutdown(). These should be called before and after alts.
I was going to update Envoy but didn't have chance to work on it.

**Comment by moderation** [comment]
Resolved by https://github.com/envoyproxy/envoy/pull/6773. Yay
