### ISSUE TITLE
compile envoy of branch 1.10.0 failed

### ISSUE THREAD

**Issue by zplinuxlover** [envoyproxy/envoy#6835]
I compile envoy of version 1.10.0 failed, the output is below

INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/service/ratelimit/v2:rls:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/config/filter/network/rate_limit/v2:rate_limit:
external/com_google_protobuf: warning: directory does not exist.
INFO: From GoLink external/com_lyft_protoc_gen_validate/linux_amd64_stripped/protoc-gen-validate [for host]:
GoLink: warning: package "github.com/golang/protobuf/ptypes/any" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/any:go_default_library
    @io_bazel_rules_go//proto/wkt:any_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
GoLink: warning: package "github.com/golang/protobuf/ptypes/duration" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/duration:go_default_library
    @io_bazel_rules_go//proto/wkt:duration_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
GoLink: warning: package "github.com/golang/protobuf/ptypes/timestamp" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/timestamp:go_default_library
    @io_bazel_rules_go//proto/wkt:timestamp_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
ERROR: /home/linuxlover/C++/envoy/source/exe/BUILD:26:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1) envoy_cc_wrapper failed: error executing command /home/linuxlover/.cache/bazel/_bazel_linuxlover/decf774929bcae4e6bd155910598679a/external/local_config_cc/extra_tools/envoy_cc_wrapper -o bazel-out/k8-dbg/bin/source/exe/envoy-static -pthread ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: internal error in write_build_id, at ../../gold/layout.cc:5542
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1220.023s, Critical Path: 98.24s
INFO: 1970 processes: 1970 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by HarinadhD** [comment]
# I'm able to build envoy-1.10.0 package with photonOS-2.0 and 3.0 but it failed for photonOS-1.0 
#below is the output -- 

INFO: From Compiling external/envoy_api/envoy/data/tap/v2alpha/http.pb.cc:
bazel-out/k8-opt/genfiles/external/envoy_api/envoy/data/tap/v2alpha/http.pb.cc:199:13: warning: 'dynamic_init_dummy_envoy_2fdata_2ftap_2fv2alpha_2fhttp_2eproto' defined but not used [-Wunused-variable]
 static bool dynamic_init_dummy_envoy_2fdata_2ftap_2fv2alpha_2fhttp_2eproto = []() { AddDescriptors_envoy_2fdata_2ftap_2fv2alpha_2fhttp_2eproto(); return true; }();
             ^
[2,667 / 2,668] Linking source/exe/envoy-static; 38s processwrapper-sandbox
**ERROR: /usr/src/photon/BUILD/envoy-v1.10.0/envoy-1.10.0/source/exe/BUILD:26:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1) envoy_cc_wrapper failed: error executing command /root/.cache/bazel/_bazel_root/8875cd1ec28c696ed4d7a4cb16d80bcf/external/local_config_cc/extra_tools/envoy_cc_wrapper -o bazel-out/k8-opt/bin/source/exe/envoy-static -pthread '-Wl,--hash-style=gnu' ... (remaining 63 argument(s) skipped)**

Use --sandbox_debug to see verbose messages from the sandbox
**/bin/ld.gold: error: cannot find -lstdc++**
bazel-out/k8-**opt/bin/source/common/common/_virtual_includes/utility_lib/common/common/utility.h:103: error: undefined reference to 'std::chrono::_V2::steady_clock::now()'
bazel-out/k8-opt/bin/source/common/common/_virtual_includes/utility_lib/common/common/utility.h:102: error: undefined reference to 'std::chrono::_V2::system_clock::now()'
external/com_github_fmtlib_fmt/include/fmt/format.h:365: error: undefined reference to 'std::runtime_error::~runtime_error()'**
external/com_github_fmtlib_fmt/include/fmt/format.h:365: error: undefined reference to 'std::runtime_error::~runtime_error()'
external/com_github_fmtlib_fmt/include/fmt/format-inl.h:930: error: undefined reference to '__cxa_allocate_exception'
external/com_github_fmtlib_fmt/include/fmt/format.h:368: error: undefined reference to 'std::runtime_error::runtime_error(char const*)'
external/com_github_fmtlib_fmt/include/fmt/format-inl.h:930: error: undefined reference to '__cxa_throw'
external/com_github_fmtlib_fmt/include/fmt/format-inl.h:930: error: undefined reference to '__cxa_free_exception'
external/com_github_fmtlib_fmt/include/fmt/format.h:2493: error: undefined reference to '__cxa_allocate_exception'
external/com_github_fmtlib_fmt/include/fmt/format.h:368: error: undefined reference to 'std::runtime_error::runtime_error(char const*)'
external/com_github_fmtlib_fmt/include/fmt/format.h:2493: error: undefined reference to '__cxa_throw'
external/com_github_fmtlib_fmt/include/fmt/format.h:2493: error: undefined reference to '__cxa_free_exception'
bazel-out/k8-opt/bin/source/exe/_virtual_includes/terminate_handler_lib/exe/terminate_handler.h:13: error: undefined reference to 'std::set_terminate(void (*)())'
source/exe/main.cc:27: error: undefined reference to '__cxa_begin_catch'
source/exe/main.cc:27: error: undefined reference to '__cxa_end_catch'
source/exe/main.cc:32: error: undefined reference to '__cxa_begin_catch'
source/exe/main.cc:33: error: undefined reference to 'std::cerr'
source/exe/main.cc:33: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/ostream:113: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'

**Comment by HarinadhD** [comment]
> #6835 envoy-1.10.0 compilation failed
> 
> I'm using below command to build envoy-1.10.0
> bazel build -c dbg //source/exe:envoy-static
> 
> Build failed , ld.gold failed to find libstd++ , So further execution failed to resolve symbols
> 
> ## below is the output
> INFO: From Compiling external/envoy_api/envoy/data/tap/v2alpha/http.pb.cc:
> bazel-out/k8-opt/genfiles/external/envoy_api/envoy/data/tap/v2alpha/http.pb.cc:199:13: warning: 'dynamic_init_dummy_envoy_2fdata_2ftap_2fv2alpha_2fhttp_2eproto' defined but not used [-Wunused-variable]
> static bool dynamic_init_dummy_envoy_2fdata_2ftap_2fv2alpha_2fhttp_2eproto = { AddDescriptors_envoy_2fdata_2ftap_2fv2alpha_2fhttp_2eproto(); return true; }();
> ^
> [2,667 / 2,668] Linking source/exe/envoy-static; 38s processwrapper-sandbox
> **ERROR: /usr/src/photon/BUILD/envoy-v1.10.0/envoy-1.10.0/source/exe/BUILD:26:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1) envoy_cc_wrapper failed: error executing command /root/.cache/bazel/_bazel_root/8875cd1ec28c696ed4d7a4cb16d80bcf/external/local_config_cc/extra_tools/envoy_cc_wrapper -o bazel-out/k8-opt/bin/source/exe/envoy-static -pthread '-Wl,--hash-style=gnu' ... (remaining 63 argument(s) skipped)**
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> **/bin/ld.gold: error: cannot find -lstdc++**
> bazel-out/k8-**opt/bin/source/common/common/_virtual_includes/utility_lib/common/common/utility.h:103: error: undefined reference to 'std::chrono::_V2::steady_clock::now()' bazel-out/k8-opt/bin/source/common/common/_virtual_includes/utility_lib/common/common/utility.h:102: error: undefined reference to 'std::chrono::_V2::system_clock::now()' external/com_github_fmtlib_fmt/include/fmt/format.h:365: error: undefined reference to 'std::runtime_error::~runtime_error()'**
> external/com_github_fmtlib_fmt/include/fmt/format.h:365: error: undefined reference to 'std::runtime_error::~runtime_error()'
> external/com_github_fmtlib_fmt/include/fmt/format-inl.h:930: error: undefined reference to '__cxa_allocate_exception'
> external/com_github_fmtlib_fmt/include/fmt/format.h:368: error: undefined reference to 'std::runtime_error::runtime_error(char const*)'
> external/com_github_fmtlib_fmt/include/fmt/format-inl.h:930: error: undefined reference to '__cxa_throw'
> external/com_github_fmtlib_fmt/include/fmt/format-inl.h:930: error: undefined reference to '__cxa_free_exception'
> external/com_github_fmtlib_fmt/include/fmt/format.h:2493: error: undefined reference to '__cxa_allocate_exception'
> external/com_github_fmtlib_fmt/include/fmt/format.h:368: error: undefined reference to 'std::runtime_error::runtime_error(char const*)'
> external/com_github_fmtlib_fmt/include/fmt/format.h:2493: error: undefined reference to '__cxa_throw'
> external/com_github_fmtlib_fmt/include/fmt/format.h:2493: error: undefined reference to '__cxa_free_exception'
> bazel-out/k8-opt/bin/source/exe/_virtual_includes/terminate_handler_lib/exe/terminate_handler.h:13: error: undefined reference to 'std::set_terminate(void (_)())' source/exe/main.cc:27: error: undefined reference to '__cxa_begin_catch' source/exe/main.cc:27: error: undefined reference to '__cxa_end_catch' source/exe/main.cc:32: error: undefined reference to '__cxa_begin_catch' source/exe/main.cc:33: error: undefined reference to 'std::cerr' source/exe/main.cc:33: error: undefined reference to 'std::basic_ostream<char, std::char_traits >& std::operator<< <std::char_traits >(std::basic_ostream<char, std::char_traits >&, char const_)'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/ostream:113: error: undefined reference to 'std::basic_ostream<char, std::char_traits >& std::endl<char, std::char_traits >(std::basic_ostream<char, std::char_traits >&)'

#issue got resolved after updating gcc version from 5+ to 6+
