### ISSUE TITLE
Failed to build Envoy under arm64 after upgrading protobuf to v23.1

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#28725]
After syncing the latest Envoy code, I could no longer build Envoy with `./ci/run_envoy_docker.sh 'bazel test --verbose_failures --config=libc++ --spawn_strategy=local ...'` on my machine, which is arm64 Mac.

Here is the build error log:
```
# Execution platform: @local_config_platform//:host
In file included from external/com_github_grpc_grpc/src/core/lib/gprpp/status_helper.cc:35:
bazel-out/aarch64-fastbuild/bin/external/com_google_protobuf/google/protobuf/any.upb.h:17:10: fatal error: 'upb/port_def.inc' file not found
#include "upb/port_def.inc"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

I have `protobuf/port_def.inc` found in the bazel directory but not `upb/port_def.inc`. So this file may be generated in the build and didn't generate, causing the build failure.

Git bisect shows me that the build is failed since 65273b2a9b25e9650a4379c9eeb0c1c48f29089c, which upgraded protobuf to v23.1.

Why is this file missing? I am not familiar with protobuf, any feedback is helpful. Thanks!

**Comment by htuch** [comment]
@phlax any thoughts?

**Comment by htuch** [comment]
https://github.com/envoyproxy/envoy/pull/28754 is probably relevant.

**Comment by phlax** [comment]
i had a quick look at this when i first saw the ticket but unfortunately the reason wasnt obvious to me - there is some kinda automagic that goes on between protobuf <> upb <> grpc, and i saw similar issues reported, but didnt get to the bottom of it

upgrading to 23.4 is definitely worth a try
