### ISSUE TITLE
A gtest change causes tests to fail.

### ISSUE THREAD

**Issue by ipuustin** [envoyproxy/envoy#5749]
**Bug Template**

*Title*: A `gtest` change causes tests to fail (for me at least).

*Description*:
Bazel tests fail.

*Repro steps*:
When I run `bazel test --verbose_failures //test/common/network/...`, I get a bunch of these errors:

    test/common/network/socket_option_factory_test.cc: In lambda function:
    test/common/network/socket_option_factory_test.cc:62:9: error: lvalue required as unary '&' operand
             EXPECT_EQ(type, input_type);
             ^~~~~~~~~
    test/common/network/socket_option_factory_test.cc:62:9: error: lvalue required as unary '&' operand
    test/common/network/socket_option_factory_test.cc:62:9: error: decltype evaluates to '<type error>', which is not a class or enumeration type
             EXPECT_EQ(type, input_type);
             ^~~~~~~~~
    test/common/network/socket_option_factory_test.cc:62:9: error: template argument 1 is invalid
             EXPECT_EQ(type, input_type);
             ^~~~~~~~~

Git bisect showed that the issue was introduced with commit 7725a97aef4412d2caba5b6077df92f487fad063.

This happens on Fedora 29 with Bazel 0.16.1.

**Comment by dnoe** [comment]
FYI @akonradi 

@ipuustin Can you indicate which compiler and version you are running?

**Comment by akonradi** [comment]
Trying to repro locally now. Not sure if it's related, but I believe Envoy targets the latest Bazel version, which is 0.22.0.

**Comment by ipuustin** [comment]
Compiler is `gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)`. I can try to update Bazel next to see if it affects this.

**Comment by ipuustin** [comment]
I upgraded Bazel and made sure the cache is cleaned but the problem persists.

However, if I use a different compiler (by setting `CC=/usr/bin/clang`), the compilation succeeds. So it looks like it could be a compiler issue with gcc.

**Comment by lizan** [comment]
I can also get this reproduced on `gcc (GCC) 8.2.1 20181127` Arch too, seems like a gcc 8.2.1 bug or a googletest bug that isn't caught in other toolchains. @akonradi

**Comment by gennadiycivil** [comment]
@akonradi I dont think we have [CI set ](https://github.com/google/googletest/blob/master/.travis.yml)for this version of gcc.

Does this code work internally?
we may consider adding this to the CI, a travis PR would be welcome.

**Comment by EricWF** [comment]
I reduced the issue (https://godbolt.org/z/wrCQ53)
```
// g++ -std=c++14
struct T { T(const int&); };
void Func(T);

void test() {
    constexpr int Val = 42;
    [Val]() { Func(Val); };
}
```

I've also gone ahead and filed a GCC bug. See http://gcc.gnu.org/PR89158
