### ISSUE TITLE
ci: clang-tidy fails and no obvious way to fix

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#10593]
CI seems to be having trouble with code/BUILD files that look correct.

One example is with failure to find a protobuf-generated include file, visible in https://github.com/envoyproxy/envoy/pull/10569 . The same PR also fails clang-tidy with a suggestion to use `= default` for a trivial constructor, but the suggestion does not appear to be correct as the constructor requires an initializer.
```
test/integration/filter_manager_integration_test.cc:14:10: error: 'test/integration/filter_manager_integration_test.pb.h' file not found [clang-diagnostic-error]
#include "test/integration/filter_manager_integration_test.pb.h"
         ^
/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/test/integration/filter_manager_integration_test.cc:444:3: error: use '= default' to define a trivial default constructor [modernize-use-equals-default,-warnings-as-errors]
  InjectDataWithEchoFilterIntegrationTest()
  ^
/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/test/integration/filter_manager_integration_test.cc:489:3: error: use '= default' to define a trivial default constructor [modernize-use-equals-default,-warnings-as-errors]
  InjectDataWithTcpProxyFilterIntegrationTest()
  ^
```

I have seen other instances too, unrelated to protobufs, where an include file cannot be found, though it's present in the other CI steps and for local builds. @antoniovicente found the same issue with `benchmark.h` in https://github.com/envoyproxy/envoy/pull/10538

**Comment by jmarantz** [comment]
@mattklein123 fyi

**Comment by antoniovicente** [comment]
I'm also seeing problems in #10538  related to cland-tidy failing when processing headers provided by external deps like the benchmark library.

**Comment by lambdai** [comment]
Another patch: https://github.com/envoyproxy/envoy/pull/10596

**Comment by lambdai** [comment]
@antoniovicente Could you check if #10596 is fixing your #10538? In some way my above PR successfully fixed a clang-tidy reported test target.

**Comment by antoniovicente** [comment]
> @antoniovicente Could you check if #10596 is fixing your #10538? In some way my above PR successfully fixed a clang-tidy reported test target.

Changes helped, but clang-tidy is still failing on said PR due to an error caused by use of a macro defined in the benchmark library.

test/server/filter_chain_benchmark_test.cc:190:20: error: initializer for base class 'Envoy::Server::FilterChainBenchmarkFixture' is redundant [readability-redundant-member-init,-warnings-as-errors]
BENCHMARK_DEFINE_F(FilterChainBenchmarkFixture, FilterChainManagerBuildTest)
                   ^

Writing fixes to clang-tidy-fixes.yaml ...
clang-tidy check failed, potentially fixed by clang-apply-replacements:
Diagnostics:
- DiagnosticMessage:
    FileOffset: 8011
    FilePath: test/server/filter_chain_benchmark_test.cc
    Message: initializer for base class 'Envoy::Server::FilterChainBenchmarkFixture'
      is redundant
    Replacements: []
  DiagnosticName: readability-redundant-member-init
MainSourceFile: ''

**Comment by lizan** [comment]
Add NOLINT there or fix .clang-tidy config by change config or remove that check?
https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-member-init.html
