### PR TITLE
Windows: test compilation refresh

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message:
Windows: test compilation refresh

- Remove TestHeaderMapImplBase constructor that takes a list of
std::pair<LowerCaseString, std::string>
  - MSVC erroneously treats this as ambiguous. It appears the explicit
  attribute of the LowerCaseString constructor is incorrectly discarded.
  We are able to reproduce this in a minimal example and see that MSVC is wrong
  here: https://godbolt.org/z/VjgsAi
  - To mitigate, remove LowerCaseString based constructor since it is
  only used in tests, tests always use std::string
- Correct use of long in envoy_quic_alarm.cc, explicitly cast to int64_t
(long on Windows is 32 bits)
- `using std::string_literal::operator""s` is erroneously rejected by
MSVC, throwing error C4455.
  - Instead, simply utilize the namespace and continue to use the
  operator as is
  - operator usage could be replaced by `std::string (const char* s,
  size_t n)` constructor
  - See https://developercommunity.visualstudio.com/content/problem/270349/warning-c4455-issued-when-using-standardized-liter.html
  and other related duplicate issues that have not yet been resolved.
- Tag tests that fail due to yaml parsing of cf/lf line endings as failing, see https://github.com/envoyproxy/envoy/issues/11659

Additional Description: N/A
Risk Level: Low
Testing: Fixes test compilation on Windows, should be a no-op for other platforms
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

File: test/test_common/utility.h [hunk 1]
```diff
@@ -757,13 +757,6 @@ template <class Interface, class Impl> class TestHeaderMapImplBase : public Inte
     }
     header_map_->verifyByteSizeInternalForTest();
   }
-  TestHeaderMapImplBase(
```
Comment (sunjayBhatia) [inline test/test_common/utility.h:760]: This was introduced by https://github.com/envoyproxy/envoy/pull/11546 cc @mattklein123 in case you have more context/if we should not remove this, the PR description has a godbolt.org link that shows the same issue we see on Windows

**Comment by sunjayBhatia** [comment]
Blocks PR https://github.com/envoyproxy/envoy/pull/11107

**Comment by sunjayBhatia** [comment]
cc @wrowe @davinci26 @nigriMSFT

**Comment by wrowe** [comment]
Local testing indicates this passes on Windows for //test/... addressing all regressions over the past week. So this is ready for review, and in combination with #11107 the CI for windows will incorporate RBE including testing.
