### ISSUE TITLE
build system error introduced in #8596

### ISSUE THREAD

**Issue by cstrahan** [envoyproxy/envoy#9987]
*Title*: build system error introduced in #8596 (known to affect 1.12.2)

*Description*:
PR #8596 introduced a regression in the build system:

```
bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/_virtual_includes/server_lib/server/config_validation/server.h:120: error: undefined reference to 'Envoy::Server::ProdListenerComponentFactory::createNetworkFilterFactoryList_(google::protobuf::RepeatedPtrField<envoy::api::v2::listener::Filter> const&, Envoy::Server::Configuration::FactoryContext&)'
bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/_virtual_includes/server_lib/server/config_validation/server.h:125: error: undefined reference to 'Envoy::Server::ProdListenerComponentFactory::createListenerFilterFactoryList_(google::protobuf::RepeatedPtrField<envoy::api::v2::listener::ListenerFilter> const&, Envoy::Server::Configuration::ListenerFactoryContext&)'
bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/_virtual_includes/server_lib/server/config_validation/server.h:130: error: undefined reference to 'Envoy::Server::ProdListenerComponentFactory::createUdpListenerFilterFactoryList_(google::protobuf::RepeatedPtrField<envoy::api::v2::listener::ListenerFilter> const&, Envoy::Server::Configuration::ListenerFactoryContext&)'
bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/listener_lib/server/listener_manager_impl.h:36: error: undefined reference to 'vtable for Envoy::Server::ProdListenerComponentFactory'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:849: error: undefined reference to 'Envoy::Server::ListenerManagerImpl::ListenerManagerImpl(Envoy::Server::Instance&, Envoy::Server::ListenerComponentFactory&, Envoy::Server::WorkerFactory&, bool)'
```

The basic premise of that PR was flawed: `listener_manager_impl.cc` and  `listener_impl.cc` still depend on each other, and _must_ be compiled as part of the same `envoy_cc_library`. Note that these two targets don't have each other listed in each's `deps`, though logically they should be; however, Bazel does _not_ support circular dependencies, so that can't be done. The only valid solution is to revert those changes.

The only reason this isn't failing as part of the official Envoy build is luck -- the linker `-l` args just so happen to be repeated such that the linker can resolve the symbols, despite the fact that these two mutually dependent libs do not explicitly specify each other as dependencies.

We have a build that uses Envoy as library and this build system error manifests there, as the code path through Bazel is just sufficiently different such that we don't enjoy the same (coincidental) arrangement of linker args.

**Comment by lambdai** [comment]
@cstrahan Sorry to see this late. Where did you see error message? 
2 compile units depend on each other is reasonable, correct? I don't fully get the circular dependency.

**Comment by cstrahan** [comment]
Could this be reopened, perhaps with some sort of no-stale flag?
