### PR TITLE
build: Disable compiler warning maybe-initialized.

### LINKED ISSUE #1341: set -fno-limit-debug-info for Clang
See https://github.com/lyft/envoy/pull/1340.

### LINKED ISSUE #2987: Envoy fails to build with GCC 7.2
Title: Envoy build fails with GCC 7.2.

Description:
```
ERROR: /root/.cache/bazel/_bazel_root/e3bb2978717df7858b43846d8c1242eb/external/envoy/source/common/upstream/BUILD:334:1: C++ compilation of rule '@envoy//source/common/upstream:upstream_lib' failed (Exit 1)
external/envoy/source/common/upstream/upstream_impl.cc: In static member function 'static Envoy::Network::ClientConnectionPtr Envoy::Upstream::HostImpl::createConnection(Envoy::Event::Dispatcher&, const Envoy::Upstream::ClusterInfo&, Envoy::Network::Address::InstanceConstSharedPtr, const OptionsSharedPtr&)':
external/envoy/source/common/upstream/upstream_impl.cc:80:67: error: '*((void*)& iftmp.712 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                           : absl::optional<bool>{}) {}
                                                                   ^
cc1plus: all warnings being treated as errors
Target //:envoy_deps failed to build
```

The failure happens due to the compiler issuing the `maybe-uninitialized` warning (enabled via `-Wall`), which is considered as an error due to `-Werror` compiler option. GCC, however, reserves the freedom of issuing false positive `maybe-uninitialized` warnings (hence the 'maybe-'), and apparently clang does not turn on `maybe-uninitialized` warning via `-Wall` for this reason.

This seems to be a well-known issue affecting `std`, `boost` and `absl` variants of `optional`, see, e.g., https://stackoverflow.com/questions/21755206/how-to-get-around-gcc-void-b-4-may-be-used-uninitialized-in-this-funct.

A potential solution would be to not issue `maybe-uninitialized` warnings also with gcc by setting `-Wno-maybe-uninitialized` after `-Wall` or at least not considering them as errors by adding the option `-Wno-error=maybe-uninitialized` after `-Werror`.

### PR DESCRIPTION
**Pull request by ggreenway**
This is causing warnings in some uses of absl::optional.

Fixes #2987
Fixes #1341

Signed-off-by: Greg Greenway <ggreenway@apple.com>

*Risk Level*: Low

*Testing*: Compiled https://github.com/envoyproxy/envoy/pull/2793 with this change, verified that build was fixed.

### CODE REVIEW

**Comment by mattklein123** [comment]
@ggreenway not sure about CI issues. Can you also note "fixes" in the description for the issue tracking this?

**Comment by ggreenway** [comment]
Looks like this is failing on clang due to errors about unknown option name. I'll sort out how to fix.

File: bazel/cc_wrapper.py [hunk 1]
```diff
@@ -64,6 +64,18 @@ def main():
         argv.append(arg)
   else:
     argv = sys.argv[1:]
+
+  # Add compiler-specific options
+  if "clang" in compiler:
+    argv.append("-fno-limit-debug-info")
+
+  if "gcc" in compiler:
```
Comment (jmillikin-stripe) [inline bazel/cc_wrapper.py]: You'll also need to check for `g++`

File: bazel/cc_wrapper.py [hunk 2]
```diff
@@ -64,6 +64,18 @@ def main():
         argv.append(arg)
   else:
     argv = sys.argv[1:]
+
+  # Add compiler-specific options
+  if "clang" in compiler:
+    argv.append("-fno-limit-debug-info")
```
Comment (jmillikin-stripe) [inline bazel/cc_wrapper.py]: Can you add a comment+ link to the github issue this flag fixes?

File: bazel/cc_wrapper.py [hunk 3]
```diff
@@ -64,6 +64,18 @@ def main():
...
+
+  if "gcc" in compiler:
+    # -Wmaybe-initialized is warning about many uses of absl::optional. Disable
+    # to prevent build breakage. This option does not exist in clang, so setting
+    # it in clang builds causes a build error because of unknown command line
+    # flag.
+    argv.append("-Wno-maybe-uninitialized")
```
Comment (jmillikin-stripe) [inline bazel/cc_wrapper.py]: Same here. IIRC there's also a GCC upstream bug report that would be good to link.

Comment (jmillikin-stripe) [reply bazel/cc_wrapper.py]: Also, per https://github.com/envoyproxy/envoy/issues/2987#issuecomment-378446114 this could be `-Wno-error=maybe-uninitialized` so potential true warnings are still visible but won't break the build.

Comment (ggreenway) [reply bazel/cc_wrapper.py]: I'm of the opinion that it will just be noise, since we know that it will print in some/many cases that we know are false-positives, so I'd rather disable the warning completely. Anyone else want to weigh in with an opinion?

Comment (mattklein123) [reply bazel/cc_wrapper.py]: I don't have a strong opinion. I agree that no one will look at the warnings so they are just noise. I'm fine with it as is.

File: bazel/cc_wrapper.py [hunk 4]
```diff
@@ -64,6 +64,21 @@ def main():
...
   else:
     argv = sys.argv[1:]
+
+  # Add compiler-specific options
+  if "clang" in compiler:
+    # This ensures that STL symbols are included.
+    # See https://github.com/envoyproxy/envoy/issues/1341
+    argv.append("-fno-limit-debug-info")
+
+  if "gcc" in compiler or "g++" in compiler:
```
Comment (jmillikin-stripe) [inline bazel/cc_wrapper.py]: https://github.com/google/oss-fuzz/issues/1337

This is incorrectly adding `-Wno-maybe-uninitialized` when CXX is `clang++`, because `"g++" in "clang++"` is true.
