### ISSUE TITLE
Build: bazel build failed on aarch64/arm64

### ISSUE THREAD

**Issue by Yikun** [envoyproxy/envoy#7686]
The envoy-build-arm64 build failure after change https://github.com/envoyproxy/envoy/pull/7555 .

Looks like we should do some upgrade on the build script? [1]

The failure log as below, and the complete log could be found in [2].
```
2019-07-17 04:36:30.704351 | ubuntu-xenial-arm64 | ERROR: /root/.cache/bazel/_bazel_root/d1453b47f357d0031ad1ec60e06d06b3/external/com_github_grpc_grpc/BUILD:470:1: Linking of rule '@com_github_grpc_grpc//:grpc_cpp_plugin' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -o bazel-out/host/bin/external/com_github_grpc_grpc/grpc_cpp_plugin -pthread -pthread -Wl,-S '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes ... (remaining 3 argument(s) skipped)
2019-07-17 04:36:30.704649 | ubuntu-xenial-arm64 |
2019-07-17 04:36:30.705050 | ubuntu-xenial-arm64 | Use --sandbox_debug to see verbose messages from the sandbox

// ... ...

2019-07-17 04:36:31.467814 | ubuntu-xenial-arm64 | bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/common.o:common.cc:function google::protobuf::internal::LogMessage::Finish(): error: undefined reference to 'std::exception::~exception()'
2019-07-17 04:36:31.468882 | ubuntu-xenial-arm64 | bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/common.o:common.cc:function google::protobuf::internal::LogMessage::Finish(): error: undefined reference to '__cxa_free_exception'
2019-07-17 04:36:31.469947 | ubuntu-xenial-arm64 | bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/common.o:common.cc:typeinfo for google::protobuf::FatalException: error: undefined reference to 'typeinfo for std::exception'
2019-07-17 04:36:31.471155 | ubuntu-xenial-arm64 | bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/repeated_field.o:repeated_field.cc:function google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int): error: undefined reference to 'typeinfo for char'
2019-07-17 04:36:31.472402 | ubuntu-xenial-arm64 | bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/repeated_field.o:repeated_field.cc:function google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int): error: undefined reference to 'typeinfo for char'
2019-07-17 04:36:31.472712 | ubuntu-xenial-arm64 | collect2: error: ld returned 1 exit status
2019-07-17 04:36:31.653533 | ubuntu-xenial-arm64 | Target //source/exe:envoy-static failed to build
2019-07-17 04:36:31.656353 | ubuntu-xenial-arm64 | Use --verbose_failures to see the command lines of failed build steps.
2019-07-17 04:36:31.766152 | ubuntu-xenial-arm64 | INFO: Elapsed time: 1057.765s, Critical Path: 218.77s
2019-07-17 04:36:31.766644 | ubuntu-xenial-arm64 | INFO: 1135 processes: 1135 linux-sandbox.
2019-07-17 04:36:31.787151 | ubuntu-xenial-arm64 | FAILED: Build did NOT complete successfully
2019-07-17 04:36:31.795969 | ubuntu-xenial-arm64 | FAILED: Build did NOT complete successfully
```

[1] https://github.com/envoyproxy/envoy/blob/master/.zuul/playbooks/envoy-build/run.yaml#L10-L23

[2] https://logs.openlabtesting.org/logs/periodic-4/16/github.com/envoyproxy/envoy/master/envoy-build-arm64/7df5468/

**Comment by Yikun** [comment]
cc @lizan

**Comment by lizan** [comment]
what version of bazel are you using?

**Comment by Yikun** [comment]
@lizan The original bazel version is `0.24`, but I also updated the bazel to latest version: `0.28.1`, and then got the same error.

**Comment by lizan** [comment]
Do you have a log based on 0.28.1? Are you pulling the same .bazelrc?

**Comment by Yikun** [comment]
> Do you have a log based on 0.28.1?

Now I try to build using bazel 0.28.1 with 14dd85d969325bb76feb85035a1668c6cbd8f6e2 , the job is running. and I will paste the error log after job complete.

> Are you pulling the same .bazelrc?

I guess no, because the env will be rebuild in every and code was reset to the 14dd85d969325bb76feb85035a1668c6cbd8f6e2

[1] https://github.com/Yikun/arm-openlab-test/pull/19

**Comment by moderation** [comment]
I had a short period with a similar issue but have compiled aarch64 today on master without issue

**Comment by Yikun** [comment]
@moderation thanks for the info, and the last job is also successful, I will try again to build the latest master.

**Comment by Yikun** [comment]
The latest result [1] is successful, the mater branch with the 0.28.1 version bazel.

[1] http://status.openlabtesting.org/build/5e25a7c9521b41779b38e69e69e868a5

**Comment by Yikun** [comment]
The arm64 build successfully in recent 3 times, so close the issue.
