### ISSUE TITLE
thousands of Duplicate symbol errors in link stage after upgraded envoy to v1.24.0

### ISSUE THREAD

**Issue by sepcon** [envoyproxy/envoy#28749]
*Title*: *thousands of Duplicate symbol errors in link stage after upgraded envoy to v1.24.0*

*Description*:
> We are building api-gateway by create a new filter which load the Go code to perform some gateway's related tasks.
We **are using envoy v1.21.2** and it's working well. But **after upgraded envoy to v1.26.4**, the build complete successfully but with thousands of **duplicate symbol errors**(>4300).
After trying some versions, we found that after the change from this commit id [deps: Bump io_bazel_rules_go -> 0.34.0](https://github.com/envoyproxy/envoy/commit/1919ff024590d84d3af0f48a1627a13e15d220d6), the issue starts occurring.  We found this on branch **release/v1.24**
We are managing to find a solution for this but impossible till now. 
could you please give us some advice this?
thanks

**Comment by phlax** [comment]
cc @doujiang24 

@sepcon can you post a sample of the error please and the command you are running

**Comment by sepcon** [comment]
hi @phlax,
we follow the filter sample project to create our own project named `gateways-x`
the command is just simple: `bazel build //:gateways-x`
after checkout the [deps: Bump io_bazel_rules_go -> 0.34.0](https://github.com/envoyproxy/envoy/commit/1919ff024590d84d3af0f48a1627a13e15d220d6) it generates 2508 duplications, but after upgraded to v1.26.4 its even worse with more than 4300. 
and below is a snippet of errors:
`duplicate symbol 'pgv::validate::validator___xds__core__v3__Resource' in:
    bazel-out/darwin_arm64-fastbuild-ST-1dd6bf738d96/bin/external/com_github_cncf_udpa/xds/core/v3/libpkg_cc_proto.lo(resource.pb.validate.o)
    bazel-out/darwin_arm64-fastbuild/bin/external/com_github_cncf_udpa/xds/core/v3/libpkg_cc_proto.lo(resource.pb.validate.o)
duplicate symbol 'xds::core::v3::Validate(xds::core::v3::Resource const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)' in:
    bazel-out/darwin_arm64-fastbuild-ST-1dd6bf738d96/bin/external/com_github_cncf_udpa/xds/core/v3/libpkg_cc_proto.lo(resource.pb.validate.o)
    bazel-out/darwin_arm64-fastbuild/bin/external/com_github_cncf_udpa/xds/core/v3/libpkg_cc_proto.lo(resource.pb.validate.o)
duplicate symbol 'pgv::validate::validator___xds__core__v3__ResourceLocator' in:
    bazel-out/darwin_arm64-fastbuild-ST-1dd6bf738d96/bin/external/com_github_cncf_udpa/xds/core/v3/libpkg_cc_proto.lo(resource_locator.pb.validate.o)
    bazel-out/darwin_arm64-fastbuild/bin/external/com_github_cncf_udpa/xds/core/v3/libpkg_cc_proto.lo(resource_locator.pb.validate.o)`

**Comment by sepcon** [comment]
We're building in `MacOS-darwin_arm64`, but the same issue with docker build ubuntu.

**Comment by phlax** [comment]
clarifying that this is a custom filter, and not the supported golang filter

**Comment by sepcon** [comment]
any suggestion to solve this @phlax ?
we are needing some latest features from envoy for our new POC, then its quite rush on solving this.

**Comment by sepcon** [comment]
issue fixed. with go_library, just add `cdeps` to interface libs only that can help to fix
