### ISSUE TITLE
Windows does not compile with clang-ci with bazel 4.2.1

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18407]

**Comment by alyssawilk** [comment]
cc @wrowe @davinci26 @phlax

**Comment by davinci26** [comment]
compilation error from the CI:

```
  C:/Program Files/LLVM/bin/clang-cl.exe @bazel-out/x64_windows-opt/bin/external/com_github_grpc_grpc/_objs/grpc_lb_policy_xds_cluster_resolver/xds_cluster_resolver.obj.params
Execution platform: @envoy_build_tools//toolchains:rbe_windows_clang_cl_platform
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: "C:/Program Files/LLVM/bin/clang-cl.exe" @bazel-out/x64_windows-opt/bin/external/com_github_grpc_grpc/_objs/grpc_lb_policy_xds_cluster_resolver/xds_cluster_resolver.obj.params
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'external/com_github_grpc_grpc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc'.
4.	Running pass 'Loop Pass Manager' on function '@"??$Insert@V?$IteratorValueAdapter@V?$allocator@UPriority@EdsUpdate@XdsApi@grpc_core@@@std@@PEAUPriority@EdsUpdate@XdsApi@grpc_core@@@inlined_vector_internal@absl@@@?$Storage@UPriority@EdsUpdate@XdsApi@grpc_core@@$01V?$allocator@UPriority@EdsUpdate@XdsApi@grpc_core@@@std@@@inlined_vector_internal@absl@@QEAAPEAUPriority@EdsUpdate@XdsApi@grpc_core@@PEBU3456@V?$IteratorValueAdapter@V?$allocator@UPriority@EdsUpdate@XdsApi@grpc_core@@@std@@PEAUPriority@EdsUpdate@XdsApi@grpc_core@@@12@_K@Z"'
5.	Running pass 'Loop Strength Reduction' on basic block '%176'
 #0 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x14b4413 C:\Program Files\LLVM\bin\clang-cl.exe 0x19620fe
 #1 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x194ac2f C:\Program Files\LLVM\bin\clang-cl.exe 0x1944d92
 #2 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x19642d1 C:\Program Files\LLVM\bin\clang-cl.exe 0x111a16e
 #3 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x147b11f C:\Program Files\LLVM\bin\clang-cl.exe 0x1480e53
 #4 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x147b720 C:\Program Files\LLVM\bin\clang-cl.exe 0x1d5de3b
 #5 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x3d709e0 C:\Program Files\LLVM\bin\clang-cl.exe 0x2f235f3
 #6 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x228b562 C:\Program Files\LLVM\bin\clang-cl.exe 0x225250c
 #7 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x22f2a2e C:\Program Files\LLVM\bin\clang-cl.exe 0x7164
 #8 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x4344 C:\Program Files\LLVM\bin\clang-cl.exe 0x21daac6
 #9 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x1accbcf C:\Program Files\LLVM\bin\clang-cl.exe 0x21da206
#10 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x20d42a7 C:\Program Files\LLVM\bin\clang-cl.exe 0x20d4839
#11 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x20bfdf6 C:\Program Files\LLVM\bin\clang-cl.exe 0x3c35
#12 0x00007ff680c64413 C:\Program Files\LLVM\bin\clang-cl.exe 0x3d8e9b8 (C:\Program Files\LLVM\bin\clang-cl.exe+0x14b4413)
#13 0x00007ff680c64413 
#14 0x00007ff680c64413 (C:\Program Files\LLVM\bin\clang-cl.exe+0x14b4413)
0x00007FF680C64413 (0x0000000000000004 0x0000001BEB582E10 0x0000000000000000 0x00007FFE5338B5C6)
0x00007FF6811120FE (0x000001DEB04951D8 0x00007FF600000000 0x0000001BEB582D30 0x00007FF67F7F0B1E)
0x00007FF6810FAC2F (0x000001DEB0247480 0x000001DE00000000 0x000001DE00000001 0x0000000000000001)
0x00007FF6810F4D92 (0xFFFFFFFFFFFFF000 0x000001DEAFD2BB70 0x0000001BEB58B3F0 0x00007FF680C2DD4A)
0x00007FF6811142D1 (0x000001DEB03228F0 0x00007FF680CFFEA4 0xCCCCCCCCCCCCCCCD 0x00007FF680C4C08A)
```
