### PR TITLE
fix build failure if OS doesn't support IPV6_TRANSPARENT

### PR DESCRIPTION
**Pull request by wgallagher**
Signed-off-by: Bill Gallagher <bgallagher@lyft.com>

Commit Message: fix build failure if OS doesn't support IPV6_TRANSPARENT
Additional Description: the build currently fails with: external/envoy/source/common/api/posix/os_sys_calls_impl.cc:145:51: error: use of undeclared identifier 'IPV6_TRANSPARENT'
Risk Level: low

### CODE REVIEW

**Comment by snowp** [comment]
I think this is right but maybe one of the reviewers of the offending PR wants to take a look? @mattklein123 @danzh2010 @chadr123

File: source/common/api/posix/os_sys_calls_impl.cc [hunk 1]
```diff
@@ -111,7 +111,7 @@ bool OsSysCallsImpl::supportsUdpGso() const {
 }
 
 bool OsSysCallsImpl::supportsIpTransparent() const {
-#if !defined(__linux__)
+#if !defined(__linux__) || !defined(IPV6_TRANSPARENT)
```
Comment (mattklein123) [inline source/common/api/posix/os_sys_calls_impl.cc:114]: You could probably just remove `!defined(__linux__)`? I don't feel strongly about it either way.

**Review by mattklein123 — APPROVED** [review]
Thanks!
