### PR TITLE
Add kae-private-key-provider build dependency

### LINKED ISSUE #41820: Add Kunpeng Accelerator Engine (KAE) support as contrib extensions
*Title*: Add Kunpeng Accelerator Engine(KAE) support as contrib extensions

*Description*:
Kunpeng Accelerator Engine (KAE) provides hardware acceleration for cryptographic operations on systems based on the Kunpeng 920 series processors.
To leverage this capability, a new Envoy contrib extension is proposed:
KAE private key provider:This extension will use the UADK lib (https://github.com/Linaro/uadk) to accelerate RSA and other asymmetric key operations used in TLS handshakes.
It will behave similarly to the existing qat private key provider, but will offload expensive cryptographic operations from the CPU to the Kunpeng hardware accelerator, freeing CPU cycles for other workloads.

A new library dependency would be added:uadklib for accessing the hardware. 

 *Relevant Links*:
https://www.hikunpeng.com/document/detail/en/kunpengaccel/kae/usermanual/kunpengaccel_16_0002.html

### PR DESCRIPTION
**Pull request by MisaKokoro**
Commit Message:Add kae-private-key-provider build dependency
Additional Description:N/A
Risk Level:N/A
Testing:N/A
Docs Changes:N/A
Release Notes:
Platform Specific Features:Arm64
Fixes #41820

### CODE REVIEW

File: bazel/repositories.bzl [hunk 1]
```diff
@@ -407,6 +407,14 @@ def _numactl():
         build_file = "@envoy//bazel/external:numactl.BUILD",
     )
 
+def _com_github_huawei_uadk():
+    external_http_archive(
+        name = "com_github_huawei_uadk",
```
Comment (phlax) [inline bazel/repositories.bzl]:
```suggestion
        name = "uadk",
```

as part of our move to bzlmod we are moving to short names for deps

related question - do you have any plans to publish this as a bzlmod module (ie here https://registry.bazel.build/)

File: api/contrib/envoy/extensions/private_key_providers/kae/v3alpha/BUILD [hunk 2]
```diff
@@ -0,0 +1,12 @@
+# DO NOT EDIT. This file is generated by tools/proto_format/proto_sync.py.
```
Comment (phlax) [inline api/contrib/envoy/extensions/private_key_providers/kae/v3alpha/BUILD:1]: im not sure i follow why you were asked to separate the dep from the code - either way, this definitely wants to land with the code

File: contrib/kae/private_key_providers/source/BUILD [hunk 3]
```diff
@@ -0,0 +1,76 @@
+load(
+    "//bazel:envoy_build_system.bzl",
+    "envoy_cc_contrib_extension",
+    "envoy_cc_library",
+    "envoy_contrib_package",
+)
```
Comment (phlax) [inline contrib/kae/private_key_providers/source/BUILD]: same with this - this definitely needs to land with the code it configures

File: contrib/kae/BUILD [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+licenses(["notice"])  # Apache 2
+
+envoy_contrib_package()
+
+# Have uadk (KAE driver) outside of any extensions because it may be used by both
+# KAE compression library extension and KAE private key provider
+# extension.
+
+configure_make(
+    name = "uadklib",
```
Comment (phlax) [inline contrib/kae/BUILD:17]: i _think_ i would prefer that this moves to `bazel/foreign_cc/BUILD`

we dont have a clear policy on this - there are some foreign_cc builds in contrib already

```console
$ git grep rules_foreign_cc -- contrib/
contrib/dlb/source/BUILD:load("@rules_foreign_cc//foreign_cc:defs.bzl", "make")
contrib/qat/BUILD:load("@rules_foreign_cc//foreign_cc:configure.bzl", "configure_make")
contrib/qat/compression/qatzip/compressor/source/BUILD:load("@rules_foreign_cc//foreign_cc:configure.bzl", "configure_make")
contrib/qat/compression/qatzstd/compressor/source/BUILD:load("@rules_foreign_cc//foreign_cc:defs.bzl", "make")

```

but i was thinking of moving them - from a dependency maintainer point of view its kinda easier to manage these builds in one place

File: contrib/kae/BUILD [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+    autogen = True,
+    configure_command = "conf.sh",
+    configure_in_place = True,
+    configure_options = [
+        "--enable-static",
```
Comment (phlax) [inline contrib/kae/BUILD:21]: one other thing im just thinking - are we building the absolute minimum required?

no reason to think otherwise - just that historically we have had issues with foreign_cc builds building a lot of unnecessary code

**Comment by phlax** [comment]
now that its separate, lets land the foreign_cc part in this pr - ie so the lib can be built - and then we can land all the code and api (and any required build config in the next)

File: contrib/kae/BUILD (hunk 5 above)
Comment (MisaKokoro) [reply contrib/kae/BUILD:21]: Yes. For the UADK library, I only need the `libwd.a` file. However, I built the entire UADK library because I’m not a maintainer of the project, and I simply followed the official documentation. I’m not sure how to build a minimal version that only produces what I need.

**Comment by MisaKokoro** [comment]
@phlax 
I’ve rearranged the code and now kept only the BUILD files related to the UADK foreign_cc parts.

File: contrib/kae/BUILD (hunk 4 above)
Comment (MisaKokoro) [reply contrib/kae/BUILD:17]: I understand, but I’m not very familiar with the Bazel build system, so I’m not sure what changes are required when moving the BUILD files into the `bazel/foreign_cc/BUILD` directory. For this commit, I didn’t change their location.

File: contrib/kae/BUILD (hunk 5 above)
Comment (phlax) [inline contrib/kae/BUILD:21]:
```suggestion
        "--enable-static",
        "--disable-shared",
```

File: contrib/kae/BUILD [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+    ],
+    lib_source = "@uadk//:all",
+    out_static_libs = [
+        "libwd.a",
+    ],
+    target_compatible_with = envoy_contrib_linux_aarch64_constraints(),
+    visibility = ["//visibility:public"],
+    # Use boringssl alias to select fips vs non-fips version.
+    deps = ["//bazel:boringssl"],
```
Comment (phlax) [inline contrib/kae/BUILD]: i suspect that ssl is needed - if that is the case this wont work by itself - if not, this shouldnt be here

File: bazel/foreign_cc/uadk.patch [hunk 7]
```diff
@@ -0,0 +1,72 @@
+diff --git a/conf.sh b/conf.sh
+index c361fbc..6a0d15d 100755
+--- a/conf.sh
++++ b/conf.sh
+@@ -4,6 +4,14 @@
+ 
+ # Build UADK into static library
+ COMPILE_TYPE="--disable-static --enable-shared"
++CC=/usr/bin/gcc
```
Comment (phlax) [inline bazel/foreign_cc/uadk.patch]: this cant happen - most of our ci uses clang - and imminently there wont even be any gcc available (other than for gcc jobs)

the platform/toolchain decides what compiler to use

File: bazel/foreign_cc/uadk.patch [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+ 	     [ have_zlib=false ])
+ AM_CONDITIONAL([HAVE_ZLIB], [test "x$have_zlib" = "xtrue"])
+ 
+-PKG_CHECK_MODULES(libcrypto, libcrypto < 3.0 libcrypto >= 1.1,
+-	     [ AC_DEFINE(HAVE_CRYPTO, 1, [Have crypto])
+-	       have_crypto=true ],
+-	     [ have_crypto=false ])
+-AM_CONDITIONAL([HAVE_CRYPTO], [test "x$have_crypto" = "xtrue"])
++# Replace pkg-config
++AC_CHECK_HEADER([openssl/crypto.h],
```
Comment (phlax) [inline bazel/foreign_cc/uadk.patch]: this is not where the boringssl header would be

File: bazel/repositories.bzl [hunk 9]
```diff
@@ -388,6 +407,14 @@ def _numactl():
         build_file = "@envoy//bazel/external:numactl.BUILD",
     )
 
+def _com_github_huawei_uadk():
```
Comment (phlax) [inline bazel/repositories.bzl]:
```suggestion
def _uadk():
```

Comment (phlax) [reply bazel/repositories.bzl]: also this needs to be called - that is what is making the arm build fail

File: bazel/foreign_cc/uadk.patch (hunk 7 above)
Comment (MisaKokoro) [reply bazel/foreign_cc/uadk.patch]: I tried building UADK with the Clang compiler, but I eventually ran into the following error:

`v1/wd_util.c:51:2: error: address argument to atomic operation must be a pointer to _Atomic type ('__u32 *' (aka 'unsigned int *') invalid)`

This issue cannot be suppressed with compiler flags. Since I cannot modify the UADK source code to fix this, the only workaround is to build it with GCC.

I also tried configuring the toolchain to use GCC, but it didn’t take effect. If there is a better way to specify the compiler, please let me know.

File: bazel/repositories.bzl (hunk 9 above)
Comment (MisaKokoro) [reply bazel/repositories.bzl]: ok,will fix it

File: bazel/foreign_cc/uadk.patch (hunk 7 above)
Comment (phlax) [reply bazel/foreign_cc/uadk.patch]: this definitely needs to be resolved - building with gcc is not an option (except specifically for gcc builds)

not sure on the best solution for this - but as a last resort you could patch the uadk source (and raise a pr upstream to resolve properly)

the compiler is specified by the user/ci - it cannot be set per build task

Comment (MisaKokoro) [reply bazel/foreign_cc/uadk.patch]: well，i try to fix it :(

**Comment by MisaKokoro** [comment]
@phlax 
It looks like the Mobile/Android job in the pipeline is currently failing, but my changes should not affect anything related to Android.  
The error shown is:
`Error: Error: Command failed: cat /tmp/tmp-1926-ggPIaoQl1yKX | jq -r -L /home/runner/work/_actions/envoyproxy/toolshed/actions-v0.3.30/gh-actions/jq/modules -f /tmp/tmp-1926-zFTfHLaZZDXk
jq: error (at <stdin>:2): Cannot index string with string "target"`
I don't really understand this.  
Is this failure caused by my modifications?

**Comment by phlax** [comment]
you just need to merge main - i made a bad commit to our ci code, but its fixed now

File: bazel/repositories.bzl (hunk 9 above)
Comment (MisaKokoro) [reply bazel/repositories.bzl]: I modified UADK’s build process and removed or adjusted several parts that would cause compilation errors under the Clang compiler. With these changes, UADK should now be able to compile successfully using Envoy’s built-in Clang toolchain.

File: bazel/foreign_cc/uadk.patch (hunk 7 above)
Comment (MisaKokoro) [reply bazel/foreign_cc/uadk.patch]: I modified UADK’s build process and removed or adjusted several parts that would cause compilation errors under the Clang compiler. With these changes, UADK should now be able to compile successfully using Envoy’s built-in Clang toolchain.

**Comment by MisaKokoro** [comment]
@phlax I reviewed the parts related to `crypto/ssl` and I believe they are not needed. I have now removed them.

**Comment by phlax** [comment]
@MisaKokoro thanks for checking - if you are confident its not required - fine

**Review by phlax — APPROVED** [review]
lgtm, thanks for iterating @MisaKokoro 

we can follow up to resolve this last point - this is still using libnuma from the system (now its getting it from our sysroot) - we should switch it to the hermetic lib - but i can do that if needed

**Comment by MisaKokoro** [comment]
@phlax The changes related to `libnuma` might be a bit tricky for you, as I’m not quite sure how to modify this part. If there’s anything you need my help with, please let me know. Thanks!
