### PR TITLE
ext_proc: send attributes

### PR DESCRIPTION
**Pull request by jbohanon**
Rework of https://github.com/envoyproxy/envoy/pull/30781 which was reverted in https://github.com/envoyproxy/envoy/pull/31017 due to ASAN fuzzer issues

The ASAN fuzzer issues are unrelated to the net-new code here and will affect any code that calls CEL `Parse`.

The main differences between this and the original PR:
- Refactored out expression/mathching code into separate util classes
- Preserve the `expr` object from which `ParsedExpr` are built per https://github.com/envoyproxy/envoy/pull/30781#discussion_r1402254604
- Conditionally fuzz the `request_attributes` and `response_attributes` fields on non-ASAN fuzzing due to unrelated issue with ASAN fuzzing in CEL parsing per https://github.com/envoyproxy/envoy/pull/31017#issuecomment-1834623505

Commit Message:
Introduce the ability to send attributes in the External Processing Request
Additional Description:
Risk Level: Low
Testing: Integration tests for request/response attributes

Release Notes: N/A
Platform Specific Features: CEL parsing will not work on Windows

### CODE REVIEW

File: source/extensions/filters/http/ext_proc/matching_utils.h [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+        response_expr_(initExpressions(response_matchers)){};
+
+  // This struct exists because the lifetime of the api expr must exceed expressions
+  // parsed from it.
+  struct ExpressionPtrWithExpr {
+    ExpressionPtrWithExpr(const google::api::expr::v1alpha1::Expr& expr,
+                          const Filters::Common::Expr::ExpressionPtr&& expr_ptr)
+        : expr_(std::move(expr)), expression_ptr_(std::move(expr_ptr)){};
+    const google::api::expr::v1alpha1::Expr& expr_;
+    const Filters::Common::Expr::ExpressionPtr& expression_ptr_;
```
Comment (ashishb-solo) [inline source/extensions/filters/http/ext_proc/matching_utils.h:31]: is `const ExpressionPtr&` the right type here? i think it should be just `ExpressionPtr` (no `const` or `&`) instead?

Comment (jbohanon) [reply source/extensions/filters/http/ext_proc/matching_utils.h]: fixed thanks!

File: source/extensions/filters/http/ext_proc/matching_utils.h [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+                    const Protobuf::RepeatedPtrField<std::string>& response_matchers)
+      : builder_(builder), request_expr_(initExpressions(request_matchers)),
+        response_expr_(initExpressions(response_matchers)){};
+
+  // This struct exists because the lifetime of the api expr must exceed expressions
+  // parsed from it.
+  struct ExpressionPtrWithExpr {
+    ExpressionPtrWithExpr(const google::api::expr::v1alpha1::Expr& expr,
+                          const Filters::Common::Expr::ExpressionPtr&& expr_ptr)
+        : expr_(std::move(expr)), expression_ptr_(std::move(expr_ptr)){};
```
[the remark this answers is not in the document]
Comment (jbohanon) [reply source/extensions/filters/http/ext_proc/matching_utils.h]: good call, fixed this

File: source/extensions/filters/http/ext_proc/ext_proc.h [hunk 3]
```diff
@@ -166,23 +179,31 @@ class FilterConfig {
...
+  }
+
+  const absl::optional<ProtobufWkt::Struct>
+  evaluateResponseAttributes(const Filters::Common::Expr::ActivationPtr& activation) const {
+    return expression_manager_.evaluateResponseAttributes(std::move(activation));
+  }
+
+  bool hasRequestExpr() const { return expression_manager_.hasRequestExpr(); }
+
+  bool hasResponseExpr() const { return expression_manager_.hasResponseExpr(); }
```
Comment (jbohanon) [inline source/extensions/filters/http/ext_proc/ext_proc.h:194]: should probably just expose the expression manager at this point
```suggestion
  const ExpressionManager& expressionManager() { return expression_manager_; }
```

File: source/extensions/filters/http/ext_proc/matching_utils.h [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+  static const absl::optional<ProtobufWkt::Struct> evaluateAttributes(
+      const Filters::Common::Expr::ActivationPtr& activation,
+      const absl::flat_hash_map<std::string, std::unique_ptr<ExpressionPtrWithExpr>>& expr) {
+    absl::optional<ProtobufWkt::Struct> proto;
+    if (!expr.empty()) {
+      proto.emplace(ProtobufWkt::Struct{});
+      for (const auto& hash_entry : expr) {
+        ProtobufWkt::Arena arena;
+        printExprPtrAndType(*hash_entry.second, "in evaluateAttributes");
+        const auto result = hash_entry.second->expression_ptr_.get()->Evaluate(*activation, &arena);
```
Comment (yuval-k) [inline source/extensions/filters/http/ext_proc/matching_utils.h:75]: style: instead of `.get()->` you should be able to  just do `->`

File: source/extensions/filters/http/ext_proc/matching_utils.cc [hunk 5]
```diff
@@ -1,37 +1,33 @@
...
-    if (matcher == "request.path") {
-      ExpressionManager::printExprPtrAndType(*expr, "after construction");
-    }
-    expressions.try_emplace(matcher, std::move(expr));
-    if (matcher == "request.path") {
-      ExpressionManager::printExprPtrAndType(*expressions.at(matcher),
-                                             "after placing in container");
-    }
+
+    auto iter = expr_list_.emplace_back(parse_status.value());
```
Comment (yuval-k) [inline source/extensions/filters/http/ext_proc/matching_utils.cc:25]: as `emplace_back` returns a reference you need to use `auto&` or it will otherwise copy

File: source/extensions/filters/http/ext_proc/matching_utils.cc [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+  absl::flat_hash_map<std::string, Filters::Common::Expr::ExpressionPtr> expressions;
+#if defined(USE_CEL_PARSER)
+  for (const auto& matcher : matchers) {
+    auto parse_status = google::api::expr::parser::Parse(matcher);
+    if (!parse_status.ok()) {
+      throw EnvoyException("Unable to parse descriptor expression: " +
+                           parse_status.status().ToString());
+    }
+
+    auto& iter = expr_list_.emplace_back(parse_status.value());
```
Comment (tyxia) [inline source/extensions/filters/http/ext_proc/matching_utils.cc:25]: There is inconsistency here: `parsed expression` will be stored in `expr_list_` for both request and response together, while the `compiled_expression` will be stored for request and response, respectively.  For example, this inconsistency could lead different behaviors in skip insertion as I comment above

How about creating new struct(like below) and use that as your hash value `absl::flat_hash_map<std::string, CelExpression>`
```
struct CelExpression {
    ParsedExpr parsed_expr_;
    ExpressionPtr compiled_expr_;
  };
 ```

**Comment by jbohanon** [comment]
@tyxia I have addressed all of your remarks in the code.

I do not currently have the cycles to dig into why CEL parsing is causing hte ASAN error. Are there similar fuzz tests run on the other instances in the code where we have to parse CEL? e.g. in the unified matcher or in the wasm filter?

File: test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc [hunk 7]
```diff
@@ -56,6 +56,19 @@ DEFINE_PROTO_FUZZER(
     ENVOY_LOG_MISC(debug, "EnvoyException during validation: {}", e.what());
     return;
   }
+
+// ASAN fuzz testing is producing an error on CEL parsing that is believed to be a false positive.
+// It is determined that the error is unrelated to the implementation of request and response
+// attributes as demonstrated here
+// https://github.com/envoyproxy/envoy/compare/main...jbohanon:envoy:bug/cel-parser-antlr-exception-use-after-free.
+// Discussion on this is located at https://github.com/envoyproxy/envoy/pull/31017
```
[the remark this answers is not in the document]
Comment (tyxia) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc:64]: > @tyxia I have addressed all of your remarks in the code.
> 
> I do not currently have the cycles to dig into why CEL parsing is causing hte ASAN error. Are there similar fuzz tests run on the other instances in the code where we have to parse CEL? e.g. in the unified matcher or in the wasm filter?

OSS fuzzer actually has fuzzing on CEL parse [here](https://github.com/google/oss-fuzz/blob/master/projects/cel-cpp/fuzz_parse.cc) and Adi's [comment](https://github.com/envoyproxy/envoy/pull/31017#issuecomment-1834527961). So, it is probably fine to submit this PR.

@kyessenov , do you know if Envoy has existing fuzz on CEL parse function or if you have seen similar fuzz issue.
TL;DR: We are seeing ASAN heap-use-after-free in CEL [parse](https://github.com/google/cel-cpp/blob/990a42878cc2a2837b1d99bd0a6fed2649f762ba/parser/parser.cc#L1074) related [callstack](https://github.com/envoyproxy/envoy/pull/31017#issuecomment-1828494408). More details can be found in this [issue](https://github.com/envoyproxy/envoy/pull/31017)

[the remark this answers is not in the document]
Comment (jbohanon) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc:64]: @tyxia @kyessenov what's the status on this?

[the remark this answers is not in the document]
Comment (tyxia) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc:64]: No one on our side has bandwidth to look at this fuzz issue. But I think I am ok with using CEL parse in ext_proc given the fact that [OSS fuzzer](https://github.com/google/oss-fuzz/blob/master/projects/cel-cpp/fuzz_parse.cc) already has fuzzing on CEL parse.

File: source/extensions/filters/http/ext_proc/matching_utils.cc [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+  }
+#else
+  ENVOY_LOG(warn, "CEL expression parsing is not available for use in this environment."
+                  " Attempted to parse " +
+                      std::to_string(matchers.size()) + " expressions");
+#endif
+  return expressions;
+}
+
+std::unique_ptr<ProtobufWkt::Struct>
```
Comment (tyxia) [inline source/extensions/filters/http/ext_proc/matching_utils.cc:43]: If you get rid of unique_ptr on the caller site, I think you can  just return `ProtobufWkt::Struct` as before.

File: source/extensions/filters/http/ext_proc/matching_utils.cc [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+    if (!parse_status.ok()) {
+      throw EnvoyException("Unable to parse descriptor expression: " +
+                           parse_status.status().ToString());
+    }
+
+    Filters::Common::Expr::ExpressionPtr expression =
+        Extensions::Filters::Common::Expr::createExpression(builder_->builder(),
+                                                            parse_status.value().expr());
+
+    CelExpression cel_expr{parse_status.value(), std::move(expression)};
```
Comment (tyxia) [inline source/extensions/filters/http/ext_proc/matching_utils.cc:32]: nit: can we omit this local variable and merge it into the line below?

**Review by tyxia — COMMENTED** [review]
Mostly LGTM, fleshing out some comments .

Thanks

File: .bazelrc [hunk 10]
```diff
@@ -417,6 +417,7 @@ build:asan-fuzzer --config=clang-asan
 build:asan-fuzzer --copt=-fno-omit-frame-pointer
 # Remove UBSAN halt_on_error to avoid crashing on protobuf errors.
 build:asan-fuzzer --test_env=UBSAN_OPTIONS=print_stacktrace=1
+build:asan-fuzzer --copt=-DASAN_FUZZER
```
[the remark this answers is not in the document]
Comment (jbohanon) [reply .bazelrc:420]: This change was to facilitate skipping the fuzzing of request/response attributes but only for the ASAN fuzzer. See [this diff](https://github.com/envoyproxy/envoy/pull/31090/files#diff-de981c7368191fd624db6f330c1df8aeb33850ae9d93e98b10dc5c0ddd6910bd) for usage. If there is a cleaner way to do this then I am happy to make the change

File: source/extensions/filters/http/ext_proc/ext_proc.cc [hunk 11]
```diff
@@ -237,7 +241,16 @@ FilterHeadersStatus Filter::decodeHeaders(RequestHeaderMap& headers, bool end_st
...
+    ProtobufWkt::Struct proto;
+
+    if (config_->expressionManager().hasRequestExpr()) {
+      auto activation_ptr = Filters::Common::Expr::createActivation(decoding_state_.streamInfo(),
+                                                                    &headers, nullptr, nullptr);
+      proto = config_->expressionManager().evaluateRequestAttributes(*activation_ptr);
+    }
+
+    status = onHeaders(decoding_state_, headers, end_stream,
+                       config_->expressionManager().hasRequestExpr() ? &proto : nullptr);
```
Comment (jbohanon) [inline source/extensions/filters/http/ext_proc/ext_proc.cc:253]: This might be a bit cleaner, but it doubles the number of places `onHeaders` may be called, which can add mental overhead when debugging and/or reading the code. WDYT @tyxia?
```suggestion
    if (config_->expressionManager().hasRequestExpr()) {
      auto activation_ptr = Filters::Common::Expr::createActivation(decoding_state_.streamInfo(),
                                                                    &headers, nullptr, nullptr);
      auto proto = config_->expressionManager().evaluateRequestAttributes(*activation_ptr);
      status = onHeaders(decoding_state_, headers, end_stream, &proto);
    } else {
      status = onHeaders(decoding_state_, headers, end_stream, nullptr);
    }
```

**Comment by jbohanon** [comment]
Thanks for the reviews @tyxia! I have addressed your latest comments and just have one question about a style preference.

Builds are now failing with the following error (I suspect due to https://github.com/envoyproxy/envoy/pull/29289)
```log
source/extensions/filters/http/ext_proc/config.cc(21): error C2664: 'Envoy::Extensions::Filters::Common::Expr::BuilderInstanceSharedPtr Envoy::Extensions::Filters::Common::Expr::getBuilder(Envoy::Server::Configuration::CommonFactoryContext &)': cannot convert argument 1 from 'Envoy::Server::Configuration::FactoryContext' to 'Envoy::Server::Configuration::CommonFactoryContext &'
```

**Comment by tyxia** [comment]
> Thanks for the reviews @tyxia! I have addressed your latest comments and just have one question about a style preference.
> 
> Builds are now failing with the following error (I suspect due to #29289)
> 
> ```
> source/extensions/filters/http/ext_proc/config.cc(21): error C2664: 'Envoy::Extensions::Filters::Common::Expr::BuilderInstanceSharedPtr Envoy::Extensions::Filters::Common::Expr::getBuilder(Envoy::Server::Configuration::CommonFactoryContext &)': cannot convert argument 1 from 'Envoy::Server::Configuration::FactoryContext' to 'Envoy::Server::Configuration::CommonFactoryContext &'
> ```

I just did some quick code search, It is probably due to https://github.com/envoyproxy/envoy/pull/31189. Will `context.serverFactoryContext()` fix the build issue?

File: source/extensions/filters/http/ext_proc/ext_proc.cc (hunk 11 above)
Comment (tyxia) [reply source/extensions/filters/http/ext_proc/ext_proc.cc:253]: TBH, either works for me. I think the code you currently have LGTM.

**Comment by jbohanon** [comment]
@tyxia @envoyproxy/dependency-shepherds @envoyproxy/api-shepherds

Looks like this is buttoned up. Anything else blocking a merge?

File: .bazelrc (hunk 10 above)
[the remark this answers is not in the document]
Comment (tyxia) [reply .bazelrc:420]: IMO, it is not ideal to introduce changes to common `.bazelrc` file just for ext_proc, especially it is temporary workaround. Is there any way to limit the change to ext_proc scope? If not, I think we can probably just skip all fuzzers when attributes are not empty, as temporary workaround

File: source/extensions/filters/http/ext_proc/matching_utils.cc [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+    }
+
+    auto proto_mut_fields = proto.mutable_fields();
+    (*proto_mut_fields)[hash_entry.first] = value;
+  }
+
+  return proto;
+}
+
+const std::vector<Matchers::StringMatcherPtr>
```
Comment (tyxia) [inline source/extensions/filters/http/ext_proc/matching_utils.cc:88]: nit : const in return type here is effectively redundant and it potentially prevent the compiler from optimizing
I think effectively `const` is used when returning pointers or references to const objects.

**Review by tyxia — COMMENTED** [review]
LGTM, modulo one nit and unresolved comment in .bazelrc. Thanks for your patience!


Defer to @yanavlasov for senior maintainer review.  Additionally, Yan please share your thoughts on this [discussion](https://github.com/envoyproxy/envoy/pull/31090/files#r1412551327 )

File: source/extensions/filters/http/ext_proc/matching_utils.cc (hunk 12 above)
Comment (jbohanon) [reply source/extensions/filters/http/ext_proc/matching_utils.cc]: Good call; removed this `const`

File: .bazelrc (hunk 10 above)
[the remark this answers is not in the document]
Comment (jbohanon) [reply .bazelrc]: Fair point. If we're okay with skipping all fuzzing I have removed it

File: test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: I am looking at the fuzzer issue. I will comment if I have some findings.

[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: After some investigation, I think the ASAN issue is within the CEL parser library: google::api::expr::parser::Parse(). 
The Envoy is using an old ANTLR version.  It is just updated by https://github.com/google/cel-cpp/commit/e14d338d0f1bc64e54c4275ac5034fe5dedba969. Let's wait for having Envoy depend on a new version CEL parser before committing this PR.

[the remark this answers is not in the document]
Comment (jbohanon) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: what is blocking that dep bump?

[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: Oh, nothing blocking. I just talked to @kyessenov. He is working on that now.

BTW, @jbohanon , if  you can pick up https://github.com/google/cel-cpp/commit/e14d338d0f1bc64e54c4275ac5034fe5dedba969 in your local workspace, and try run: "bazel test --config asan-fuzzer //test/extensions/filters/http/ext_proc/unit_test_fuzz:ext_proc_unit_test_fuzz --test_timeout=300", and let us know the results, that will be good information.  We are not 100% sure this can fix it,  just think it's a possibility.

[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: https://github.com/envoyproxy/envoy/pull/31456/

[the remark this answers is not in the document]
Comment (jbohanon) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: Alas, merging @kyessenov's branch did not resolve the `heap-use-after-free` in `google::api::expr::parser::Parse`

[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc]: There are separate efforts which are continue investigating why Envoy fuzzer is crashing when calling this function.    I am ok to not blocking this PR due to that issue.

File: source/extensions/filters/http/ext_proc/matching_utils.cc [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+namespace Extensions {
+namespace HttpFilters {
+namespace ExternalProcessing {
+
+absl::flat_hash_map<std::string, Filters::Common::Expr::ExpressionPtr>
+ExpressionManager::initExpressions(const Protobuf::RepeatedPtrField<std::string>& matchers) {
+  absl::flat_hash_map<std::string, Filters::Common::Expr::ExpressionPtr> expressions;
+#if defined(USE_CEL_PARSER)
+  for (const auto& matcher : matchers) {
+    auto parse_status = google::api::expr::parser::Parse(matcher);
```
[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply source/extensions/filters/http/ext_proc/matching_utils.cc:22]: Do we need some basic string validation for "matcher", for example, it does not contain non-utf8 characters, it doesn't contain \0, \n, \r, et. al

File: source/extensions/filters/http/ext_proc/ext_proc.cc [hunk 14]
```diff
@@ -221,7 +221,8 @@ void Filter::onDestroy() {
 }
 
 FilterHeadersStatus Filter::onHeaders(ProcessorState& state,
-                                      Http::RequestOrResponseHeaderMap& headers, bool end_stream) {
+                                      Http::RequestOrResponseHeaderMap& headers, bool end_stream,
+                                      ProtobufWkt::Struct* proto) {
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/ext_proc.cc:225]: This should be pass by reference.

Comment (jbohanon) [reply source/extensions/filters/http/ext_proc/ext_proc.cc:225]: We use `nullptr` to indicate that attributes are not configured. This is on Line 243

**Comment by jbohanon** [comment]
It appears that the `Mobile/Android` check is broken on some unrelated toolchain issues

**Review by tyxia — APPROVED** [review]
LGTM, Thank you for your patience! Nice work

**Comment by tyxia** [comment]
defer to @yanavlasov for final review and merge. PTAL, Thanks

**Comment by linsun** [comment]
@yanavlasov a friendly ping for final review and merge when you get a chance? Thx!

**Review by yanavlasov — APPROVED** [review]
