### ISSUE TITLE
What is causing v1.30.2 to fail build?

### ISSUE THREAD

**Issue by harrisonlhl123** [envoyproxy/envoy#35525]
Description: I am working with v1.30.2 on MacOS and when I run ```ci/mac_ci_steps.sh``` the build fails with this error:
```
make[6]: Entering directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir/glib/glib'
  CC       libglib_2_0_la-gallocator.lo
  CC       libglib_2_0_la-gcache.lo
  CC       libglib_2_0_la-gcompletion.lo
  CC       libglib_2_0_la-grel.lo
  CC       libglib_2_0_la-gthread-deprecated.lo
  CC       libglib_2_0_la-garray.lo
  CC       libglib_2_0_la-gasyncqueue.lo
  CC       libglib_2_0_la-gatomic.lo
gatomic.c:392:10: error: incompatible integer to pointer conversion passing 'gssize' (aka 'long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
  return g_atomic_pointer_add ((volatile gpointer *) atomic, val);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:170:46: note: expanded from macro 'g_atomic_pointer_add'
    (gssize) __sync_fetch_and_add ((atomic), (val));                         \
                                             ^~~~~
gatomic.c:416:10: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
  return g_atomic_pointer_and ((volatile gpointer *) atomic, val);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:177:45: note: expanded from macro 'g_atomic_pointer_and'
    (gsize) __sync_fetch_and_and ((atomic), (val));                          \
                                            ^~~~~
gatomic.c:440:10: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
  return g_atomic_pointer_or ((volatile gpointer *) atomic, val);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:184:44: note: expanded from macro 'g_atomic_pointer_or'
    (gsize) __sync_fetch_and_or ((atomic), (val));                           \
                                           ^~~~~
gatomic.c:464:10: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
  return g_atomic_pointer_xor ((volatile gpointer *) atomic, val);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:191:45: note: expanded from macro 'g_atomic_pointer_xor'
    (gsize) __sync_fetch_and_xor ((atomic), (val));                          \
                                            ^~~~~
4 errors generated.
make[6]: *** [Makefile:1317: libglib_2_0_la-gatomic.lo] Error 1
make[6]: Leaving directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir/glib/glib'
make[5]: *** [Makefile:1934: all-recursive] Error 1
make[5]: Leaving directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir/glib/glib'
make[4]: *** [Makefile:953: all] Error 2
make[4]: Leaving directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir/glib/glib'
make[3]: *** [Makefile:1046: all-recursive] Error 1
make[3]: Leaving directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir/glib'
make[2]: *** [Makefile:770: all] Error 2
make[2]: Leaving directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir/glib'
make[1]: *** [Makefile:707: all-recursive] Error 1
make[1]: Leaving directory '/private/var/tmp/_bazel_hliang/743e5c2717252e3847ab3895fca3effc/sandbox/darwin-sandbox/4562/execroot/envoy/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig.build_tmpdir'
make: *** [Makefile:463: all] Error 2
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig_tool_default_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig_tool_default_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/pkgconfig_tool_default_foreign_cc/BootstrapPkgConfig.log

Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 101.395s, Critical Path: 80.22s
INFO: 3919 processes: 3682 remote cache hit, 188 internal, 49 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

I ran the same command for the latest version (v1.31.0), and it works fine. Can someone explain the reason for failure and what file(s) to update in v1.30.2 to fix this?

**Comment by thenewwazoo** [comment]
Sorry for not having a clearer fix, but this problem is related to pkg_config having an ancient version of glib vendored. To work around it, you can [set the following flags](https://github.com/thenewwazoo/envoy-dynamic-modules/commit/d10b06c60ed6eced02eced07a67c12bfbbf35402#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832fR149) in your .bazelrc:

```
# workaround for pkg_config's glib dep being ancien
# from https://github.com/bazelbuild/rules_foreign_cc/issues/1186#issuecomment-2053550487
# see https://github.com/bazelbuild/rules_foreign_cc/issues/1065
build:macos --host_action_env=CXXFLAGS=-Wno-int-conversion
build:macos --action_env=CXXFLAGS=-Wno-int-conversion
build:macos --host_action_env=CFLAGS=-Wno-int-conversion
build:macos --action_env=CFLAGS=-Wno-int-conversion
```

**Comment by phlax** [comment]
i thought we had a fix for that (which just got removed i think) - maybe we just never backported the fix

**Comment by harrisonlhl123** [comment]
That worked, thanks!🙌
