### ISSUE TITLE
FIPS build failing in v1.34

### ISSUE THREAD

**Issue by kaih-w** [envoyproxy/envoy#39821]
*FIPS build failing in v1.34*: *Failure is related to missing quiche header files even with build and test filter tag nofips*

*Description*:
When trying to build the FIPS variant of Envoy v1.34, I get a build failure regarding missing header files from the quiche library. I can build non-FIPS Envoy without issue.

*Repro steps*:
The operating system is Amazon Linux 2023, but I am using the envoy build container -- `./ci/run_envoy_docker.sh './ci/do_ci.sh sizeopt'` -- to run the build. In order to run the FIPS build I have been setting these environment variables before running the envoy build container:
```
export BAZEL_BUILD_EXTRA_OPTIONS="--define boringssl=fips --build_tag_filters=-nofips"

export BAZEL_EXTRA_TEST_OPTIONS="--test_tag_filters=-nofips"
```

Envoy seems to compile fine, but around integration test 15, I get this failure:
```
In file included from source/common/quic/send_buffer_monitor.cc:1:
./source/common/quic/send_buffer_monitor.h:3:10: fatal error: 'quiche/quic/core/quic_stream.h' file not found
    3 | #include "quiche/quic/core/quic_stream.h"
```

**Comment by RyanTheOptimist** [comment]
cc: @KBaichoo

**Comment by RyanTheOptimist** [comment]
cc: @agrawroh

**Comment by KBaichoo** [comment]
Can you give it another shot at HEAD @kaih-w given https://github.com/envoyproxy/envoy/pull/39809 ?

**Comment by kaih-w** [comment]
Looks like FIPS builds at HEAD, but I'm trying to release a stable Envoy version within our service. Would it make sense to apply #39809 as a patch to v1.34?

**Comment by KBaichoo** [comment]
>Would it make sense to apply https://github.com/envoyproxy/envoy/pull/39809 as a patch to v1.34?

Yes backporting it to [1.34.1](https://github.com/envoyproxy/envoy/commits/v1.34.1/) (it'd be release as 1.34.2) seems reasonable. Could you help with that?

**Comment by agrawroh** [comment]
@kaih-w Would it be possible for you to try using the `release/v1.34` HEAD and see if the issue is resolved now?

**Comment by kaih-w** [comment]
@agrawroh Successfully ran a FIPS build using release/v1.34 HEAD, thanks for taking care of the backport. @KBaichoo I'd love to help as I want to start contributing back, so let me know if there's anything else I can help with. Thank you all for taking the time to look into this!
